import funciones_tarea_1

def test_caract():
    assert funciones_tarea_1.string_work("abcdefghIJKLMNOPQRSTUVWXYZ") == "ABCDEFGHijklmnopqrstuvwxyz"

def test_error_con_numero():
    assert funciones_tarea_1.string_work(10) == 505

def test_error_numsim():
    assert funciones_tarea_1.string_work("abc$") == 506

def test_prueba_todos():
    assert funciones_tarea_1.num_to_str(0) == "cero"
    assert funciones_tarea_1.num_to_str(1) == "uno"
    assert funciones_tarea_1.num_to_str(2) == "dos"
    assert funciones_tarea_1.num_to_str(3) == "tres"
    assert funciones_tarea_1.num_to_str(4) == "cuatro"
    assert funciones_tarea_1.num_to_str(5) == "cinco"
    assert funciones_tarea_1.num_to_str(6) == "seis"
    assert funciones_tarea_1.num_to_str(7) == "siete"
    assert funciones_tarea_1.num_to_str(8) == "ocho"
    assert funciones_tarea_1.num_to_str(9) == "nueve"
    assert funciones_tarea_1.num_to_str(10) == "diez"
    assert funciones_tarea_1.num_to_str(11) == "once"
    assert funciones_tarea_1.num_to_str(12) == "doce"
    assert funciones_tarea_1.num_to_str(13) == "trece"
    assert funciones_tarea_1.num_to_str(14) == "catorce"
    assert funciones_tarea_1.num_to_str(15) == "quince"
    assert funciones_tarea_1.num_to_str(16) == "dieciseis"
    assert funciones_tarea_1.num_to_str(17) == "diecisiete"
    assert funciones_tarea_1.num_to_str(18) == "dieciocho"
    assert funciones_tarea_1.num_to_str(19) == "diecinueve"
    assert funciones_tarea_1.num_to_str(20) == "veinte"
    assert funciones_tarea_1.num_to_str(21) == "veinte_y_uno"
    assert funciones_tarea_1.num_to_str(22) == "veinte_y_dos"
    assert funciones_tarea_1.num_to_str(23) == "veinte_y_tres"
    assert funciones_tarea_1.num_to_str(24) == "veinte_y_cuatro"
    assert funciones_tarea_1.num_to_str(25) == "veinte_y_cinco"
    assert funciones_tarea_1.num_to_str(26) == "veinte_y_seis"
    assert funciones_tarea_1.num_to_str(27) == "veinte_y_siete"
    assert funciones_tarea_1.num_to_str(28) == "veinte_y_ocho"
    assert funciones_tarea_1.num_to_str(29) == "veinte_y_nueve"
    assert funciones_tarea_1.num_to_str(30) == "treinta"
    assert funciones_tarea_1.num_to_str(31) == "treinta_y_uno"
    assert funciones_tarea_1.num_to_str(32) == "treinta_y_dos"
    assert funciones_tarea_1.num_to_str(33) == "treinta_y_tres"
    assert funciones_tarea_1.num_to_str(34) == "treinta_y_cuatro"
    assert funciones_tarea_1.num_to_str(35) == "treinta_y_cinco"
    assert funciones_tarea_1.num_to_str(36) == "treinta_y_seis"
    assert funciones_tarea_1.num_to_str(37) == "treinta_y_siete"
    assert funciones_tarea_1.num_to_str(38) == "treinta_y_ocho"
    assert funciones_tarea_1.num_to_str(39) == "treinta_y_nueve"
    assert funciones_tarea_1.num_to_str(40) == "cuarenta"
    assert funciones_tarea_1.num_to_str(41) == "cuarenta_y_uno"
    assert funciones_tarea_1.num_to_str(42) == "cuarenta_y_dos"
    assert funciones_tarea_1.num_to_str(43) == "cuarenta_y_tres"
    assert funciones_tarea_1.num_to_str(44) == "cuarenta_y_cuatro"
    assert funciones_tarea_1.num_to_str(45) == "cuarenta_y_cinco"
    assert funciones_tarea_1.num_to_str(46) == "cuarenta_y_seis"
    assert funciones_tarea_1.num_to_str(47) == "cuarenta_y_siete"
    assert funciones_tarea_1.num_to_str(48) == "cuarenta_y_ocho"
    assert funciones_tarea_1.num_to_str(49) == "cuarenta_y_nueve"
    assert funciones_tarea_1.num_to_str(50) == "cincuenta"
    assert funciones_tarea_1.num_to_str(51) == "cincuenta_y_uno"
    assert funciones_tarea_1.num_to_str(52) == "cincuenta_y_dos"
    assert funciones_tarea_1.num_to_str(53) == "cincuenta_y_tres"
    assert funciones_tarea_1.num_to_str(54) == "cincuenta_y_cuatro"
    assert funciones_tarea_1.num_to_str(55) == "cincuenta_y_cinco"
    assert funciones_tarea_1.num_to_str(56) == "cincuenta_y_seis"
    assert funciones_tarea_1.num_to_str(57) == "cincuenta_y_siete"
    assert funciones_tarea_1.num_to_str(58) == "cincuenta_y_ocho"
    assert funciones_tarea_1.num_to_str(59) == "cincuenta_y_nueve"
    assert funciones_tarea_1.num_to_str(60) == "sesenta"
    assert funciones_tarea_1.num_to_str(61) == "sesenta_y_uno"
    assert funciones_tarea_1.num_to_str(62) == "sesenta_y_dos"
    assert funciones_tarea_1.num_to_str(63) == "sesenta_y_tres"
    assert funciones_tarea_1.num_to_str(64) == "sesenta_y_cuatro"
    assert funciones_tarea_1.num_to_str(65) == "sesenta_y_cinco"
    assert funciones_tarea_1.num_to_str(66) == "sesenta_y_seis"
    assert funciones_tarea_1.num_to_str(67) == "sesenta_y_siete"
    assert funciones_tarea_1.num_to_str(68) == "sesenta_y_ocho"
    assert funciones_tarea_1.num_to_str(69) == "sesenta_y_nueve"
    assert funciones_tarea_1.num_to_str(70) == "setenta"
    assert funciones_tarea_1.num_to_str(71) == "setenta_y_uno"
    assert funciones_tarea_1.num_to_str(72) == "setenta_y_dos"
    assert funciones_tarea_1.num_to_str(73) == "setenta_y_tres"
    assert funciones_tarea_1.num_to_str(74) == "setenta_y_cuatro"
    assert funciones_tarea_1.num_to_str(75) == "setenta_y_cinco"
    assert funciones_tarea_1.num_to_str(76) == "setenta_y_seis"
    assert funciones_tarea_1.num_to_str(77) == "setenta_y_siete"
    assert funciones_tarea_1.num_to_str(78) == "setenta_y_ocho"
    assert funciones_tarea_1.num_to_str(79) == "setenta_y_nueve"
    assert funciones_tarea_1.num_to_str(80) == "ochenta"
    assert funciones_tarea_1.num_to_str(81) == "ochenta_y_uno"
    assert funciones_tarea_1.num_to_str(82) == "ochenta_y_dos"
    assert funciones_tarea_1.num_to_str(83) == "ochenta_y_tres"
    assert funciones_tarea_1.num_to_str(84) == "ochenta_y_cuatro"
    assert funciones_tarea_1.num_to_str(85) == "ochenta_y_cinco"
    assert funciones_tarea_1.num_to_str(86) == "ochenta_y_seis"
    assert funciones_tarea_1.num_to_str(87) == "ochenta_y_siete"
    assert funciones_tarea_1.num_to_str(88) == "ochenta_y_ocho"
    assert funciones_tarea_1.num_to_str(89) == "ochenta_y_nueve"
    assert funciones_tarea_1.num_to_str(90) == "noventa"
    assert funciones_tarea_1.num_to_str(91) == "noventa_y_uno"
    assert funciones_tarea_1.num_to_str(92) == "noventa_y_dos"
    assert funciones_tarea_1.num_to_str(93) == "noventa_y_tres"
    assert funciones_tarea_1.num_to_str(94) == "noventa_y_cuatro"
    assert funciones_tarea_1.num_to_str(95) == "noventa_y_cinco"
    assert funciones_tarea_1.num_to_str(96) == "noventa_y_seis"
    assert funciones_tarea_1.num_to_str(97) == "noventa_y_siete"
    assert funciones_tarea_1.num_to_str(98) == "noventa_y_ocho"
    assert funciones_tarea_1.num_to_str(99) == "noventa_y_nueve"
    
    


def test_str_error():
    assert funciones_tarea_1.num_to_str("Hola mundo") == 101

def test_num_mayor():
    assert funciones_tarea_1.num_to_str(100) == 103


